defaults:
  - override hydra/job_logging: custom

processing:
  device: cuda
  image_width: 160
  image_height: 75

training:
  lr: 3e-4
  batch_size: 8
  num_workers: 4
  num_epochs: 200

bools:
  DISPLAY_ONLY_WRONG_PREDICTIONS: true
  VIEW_INFERENCE_WHILE_TRAINING: true
  SAVE_CHECKPOINTS: true

paths:
  dataset_glob: ./dataset/???????.png
  save_model_as: ./logs/csdd
  save_dir: ./logs

model:
  use_attention: true
  use_ctc: true
  gray_scale: true
  dims: 256
