defaults:
  - override hydra/job_logging: custom

processing:
  device: cpu
  image_width: 160 # default: 320
  image_height: 75 # default: 150

training:
  lr: 9e-4 # default: 3e-4
  batch_size: 8
  num_workers: 8
  num_epochs: 200

bools:
  DISPLAY_ONLY_WRONG_PREDICTIONS: true
  VIEW_INFERENCE_WHILE_TRAINING: true
  SAVE_CHECKPOINTS: true

paths:
  dataset_dir: ./dataset
  save_model_as: ./logs/csdd
  save_dir: ./logs

model:
  use_attention: true
  use_ctc: true
  gray_scale: true
  dims: 64 # default 256
